version: "3.9"

networks:
  frontend:
    name: mc-bedrock_network

services:
  mc-bedrock-survival:
    container_name: mc-bedrock-survival
    image: itzg/minecraft-bedrock-server:latest
    networks:
      frontend:
    ports:
      - "19232:19132/udp"
    volumes:
      - "/volume1/docker/minecraft-bedrock-survival:/data"
    environment:
      EULA: "true"
      TZ: "America/Chicago"
      VERSION: "LATEST"
      DIFFICULTY: "normal"
      OPS: "2533274807956973"
      PVP: "true"
      GAMEMODE: "survival"
      SERVER_NAME: "MHD Bedrock Survival"
      ALLOW_CHEATS: "true"
    restart: unless-stopped
  mc-bedrock-creative:
    container_name: mc-bedrock-creative
    image: itzg/minecraft-bedrock-server:latest
    networks:
      frontend:
    ports:
      - "19132:19132/udp"
    volumes:
      - "/volume1/docker/minecraft-bedrock-creative:/data"
    environment:
      EULA: "true"
      TZ: "America/Chicago"
      VERSION: "LATEST"
      OPS: "2533274807956973"
      GAMEMODE: "creative"
      SERVER_NAME: "MHD Bedrock Creative"
    restart: unless-stopped
